----------------------------------------
-- UI TYPE MODULE SCRIPT 
-- @carsondev7
----------------------------------------

local UIType = {
	WaitingForPlayers = "WaitingForPlayers",
	Intermission = "Intermission",
	MapDisplay = "MapDisplay",
	NewDisasterStarting = "NewDisasterStarting",
	DisasterInProgress = "DisasterInProgress",
	RoundOver = "RoundOver",
	DeathFeed = "DeathFeed",
	UpdateTokens = "UpdateTokens",
}

return UIType
